#!/bin/bash
# ============================================================
#  SUPPLIO — SystemSettings Sync Payload Generator
#  Terms/Privacy/Contract matnlari uchun schema-safe SQL yaratadi
# ============================================================

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
RESET="\033[0m"

log()  { echo -e "${CYAN}[SYNC]${RESET}   $1"; }
ok()   { echo -e "${GREEN}[OK]${RESET}    $1"; }
warn() { echo -e "${YELLOW}[WARN]${RESET}  $1"; }
fail() { echo -e "${RED}[ERROR]${RESET} $1"; exit 1; }

# 1. Local DB ma'lumotlari
# Ustuvorlik: 1) argument 2) env 3) .env fayl 4) fallback
if [ -n "$1" ]; then
    DB_URL="$1"
elif [ -n "$DATABASE_URL" ]; then
    DB_URL="$DATABASE_URL"
elif [ -f "backend/.env" ]; then
    DB_URL=$(grep "^DATABASE_URL=" backend/.env | cut -d'=' -f2- | sed 's/^"//; s/"$//')
elif [ -f "backend/.env.production" ]; then
    DB_URL=$(grep "^DATABASE_URL=" backend/.env.production | cut -d'=' -f2- | sed 's/^"//; s/"$//')
fi

if [ -z "$DB_URL" ]; then
    DB_URL="postgresql://postgres:2007@127.0.0.1:5432/supplio_main"
fi

# Prisma URL dagi query parametrlar (masalan ?schema=public) pg_dump uchun muammo beradi.
DB_URL_CLEAN="${DB_URL%%\?*}"
DB_SCHEMA=$(echo "$DB_URL" | sed -n 's/.*[?&]schema=\([^&]*\).*/\1/p')
if [ -z "$DB_SCHEMA" ]; then
    DB_SCHEMA="public"
fi
PAYLOAD_FILE="system_settings_payload.sql"

log "SystemSettings sync payload tayyorlanmoqda..."
log "Schema: $DB_SCHEMA"

# SystemSettings mavjudligi va terms qiymati tekshiruvi.
SETTINGS_INFO=$(psql "$DB_URL_CLEAN" -At -c "SELECT COUNT(*), COALESCE(MAX(GREATEST(length(COALESCE(\"termsUz\",'')), length(COALESCE(\"termsRu\",'')), length(COALESCE(\"termsEn\",'')), length(COALESCE(\"privacyUz\",'')), length(COALESCE(\"privacyRu\",'')), length(COALESCE(\"privacyEn\",'')))),0) FROM \"$DB_SCHEMA\".\"SystemSettings\";" 2>/dev/null)
if [ -z "$SETTINGS_INFO" ]; then
    fail "SystemSettings jadvali o'qilmadi. DB/schema noto'g'ri bo'lishi mumkin."
fi

SETTINGS_ROWS=$(echo "$SETTINGS_INFO" | cut -d'|' -f1)
MAX_TEXT_LEN=$(echo "$SETTINGS_INFO" | cut -d'|' -f2)

if [ "$SETTINGS_ROWS" = "0" ] || [ "$MAX_TEXT_LEN" = "0" ]; then
    fail "Lokal DBda SystemSettings matnlari bo'sh yoki qator yo'q. Avval local datani to'ldiring."
fi

log "SystemSettings qatori: $SETTINGS_ROWS, max matn uzunligi: $MAX_TEXT_LEN"

TERMS_UZ=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"termsUz\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
TERMS_RU=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"termsRu\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
TERMS_EN=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"termsEn\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
TERMS_UZ_CYR=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"termsUzCyr\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
PRIVACY_UZ=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"privacyUz\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
PRIVACY_RU=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"privacyRu\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
PRIVACY_EN=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"privacyEn\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
PRIVACY_UZ_CYR=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"privacyUzCyr\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
CONTRACT_UZ=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"contractUz\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
CONTRACT_RU=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"contractRu\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
CONTRACT_EN=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"contractEn\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")
CONTRACT_UZ_CYR=$(psql "$DB_URL_CLEAN" -At -c "SELECT quote_nullable(\"contractUzCyr\") FROM \"$DB_SCHEMA\".\"SystemSettings\" WHERE id='GLOBAL' LIMIT 1;")

cat > "$PAYLOAD_FILE" <<EOF
-- Auto-generated by db_sync_selective.sh
DO \$sync\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "SystemSettings" WHERE id = 'GLOBAL') THEN
        INSERT INTO "SystemSettings" (id, "updatedAt") VALUES ('GLOBAL', NOW());
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'termsUz') THEN
        UPDATE "SystemSettings" SET "termsUz" = ${TERMS_UZ} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'termsRu') THEN
        UPDATE "SystemSettings" SET "termsRu" = ${TERMS_RU} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'termsEn') THEN
        UPDATE "SystemSettings" SET "termsEn" = ${TERMS_EN} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'termsUzCyr') THEN
        UPDATE "SystemSettings" SET "termsUzCyr" = ${TERMS_UZ_CYR} WHERE id = 'GLOBAL';
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'privacyUz') THEN
        UPDATE "SystemSettings" SET "privacyUz" = ${PRIVACY_UZ} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'privacyRu') THEN
        UPDATE "SystemSettings" SET "privacyRu" = ${PRIVACY_RU} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'privacyEn') THEN
        UPDATE "SystemSettings" SET "privacyEn" = ${PRIVACY_EN} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'privacyUzCyr') THEN
        UPDATE "SystemSettings" SET "privacyUzCyr" = ${PRIVACY_UZ_CYR} WHERE id = 'GLOBAL';
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'contractUz') THEN
        UPDATE "SystemSettings" SET "contractUz" = ${CONTRACT_UZ} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'contractRu') THEN
        UPDATE "SystemSettings" SET "contractRu" = ${CONTRACT_RU} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'contractEn') THEN
        UPDATE "SystemSettings" SET "contractEn" = ${CONTRACT_EN} WHERE id = 'GLOBAL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'SystemSettings' AND column_name = 'contractUzCyr') THEN
        UPDATE "SystemSettings" SET "contractUzCyr" = ${CONTRACT_UZ_CYR} WHERE id = 'GLOBAL';
    END IF;
END
\$sync\$;
EOF

if [ $? -eq 0 ]; then
        ok "Sync payload yaratildi: $PAYLOAD_FILE"
else
        fail "Payload yaratishda xatolik!"
fi

# File hajmini ko'rsatish
SIZE=$(du -h "$PAYLOAD_FILE" | cut -f1)
log "Fayl hajmi: $SIZE"

# 2. GitHub'ga yuborish
log "GitHub'ga yuklanmoqda..."
git add "$PAYLOAD_FILE"
git commit -m "chore: system settings sync payload $(date +'%Y-%m-%d %H:%M:%S')"

if git push origin main; then
    ok "GitHub'ga yuborildi."
else
    warn "Push qilishda xatolik yuz berdi. Qo'lda pull qiling va qayta urining."
    exit 1
fi

echo ""
echo "=========================================================="
echo " ✓ TAYYOQ! Endi serverdagi 'bash restore_selective.sh' ni ishlating"
echo "=========================================================="
